# Generated by Django 5.2.7 on 2025-11-16 23:00

import os
from django.db import migrations
from django.contrib.sites.models import Site

def add_google_social_app(apps, schema_editor):
    """
    Creates the Google SocialApp and configures the default site.
    """
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    Site = apps.get_model('sites', 'Site')

    # Get Google credentials from environment variables
    client_id = os.getenv("GOOGLE_CLIENT_ID")
    secret = os.getenv("GOOGLE_CLIENT_SECRET")

    # Ensure credentials are set
    if not client_id or not secret:
        raise ValueError(
            "GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET must be set in your .env file."
        )

    # Create or update the default site
    site, created = Site.objects.get_or_create(
        id=1, 
        defaults={'domain': 'example.com', 'name': 'example.com'}
    )
    if not created:
        site.domain = 'example.com'
        site.name = 'example.com'
        site.save()

    # Create the Google SocialApp
    google_app, created = SocialApp.objects.get_or_create(
        provider='google',
        defaults={
            'name': 'Google',
            'client_id': client_id,
            'secret': secret,
        }
    )
    
    # Add the site to the SocialApp
    google_app.sites.add(site)
    google_app.save()

def remove_google_social_app(apps, schema_editor):
    """
    Removes the Google SocialApp.
    """
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    try:
        google_app = SocialApp.objects.get(provider='google')
        google_app.delete()
    except SocialApp.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_user'),
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(add_google_social_app, remove_google_social_app),
    ]
