from django.urls import path
from .views import (
    lawyer_list_view,
    lawyer_detail_view,
    connect_with_lawyer_view,
    lawyer_dashboard_view,
    lawyer_connection_update_view,
    withdraw_connection_view,
    connection_requests_list_view,
    update_lawyer_availability_view,
    submit_review_view,
    lawyer_reviews_view,
    check_review_status_view,
    update_case_status_view,
    lawyer_match_view,
    my_lawyer_profile_view,
    update_quick_reply_templates_view,
    export_consultations_view,
)

urlpatterns = [
    path('', lawyer_list_view, name='lawyer_list'),
    path('match/', lawyer_match_view, name='lawyer_match'),
    path('dashboard/', lawyer_dashboard_view, name='lawyer_dashboard'),
    path('my-profile/', my_lawyer_profile_view, name='my_lawyer_profile'),
    path('availability/', update_lawyer_availability_view, name='update_lawyer_availability'),
    path('quick-replies/', update_quick_reply_templates_view, name='update_quick_reply_templates'),
    path('export-consultations/', export_consultations_view, name='export_consultations'),
    path('connections/', connection_requests_list_view, name='connection_requests_list'),
    path('connections/<str:connection_id>/', lawyer_connection_update_view, name='lawyer_connection_update'),
    path('connections/<str:connection_id>/withdraw/', withdraw_connection_view, name='withdraw_connection'),
    path('connections/<str:connection_id>/review/', submit_review_view, name='submit_review'),
    path('connections/<str:connection_id>/review/check/', check_review_status_view, name='check_review'),
    path('connections/<str:connection_id>/case/', update_case_status_view, name='update_case_status'),
    path('<str:lawyer_id>/', lawyer_detail_view, name='lawyer_detail'),
    path('<str:lawyer_id>/connect/', connect_with_lawyer_view, name='connect_lawyer'),
    path('<str:lawyer_id>/reviews/', lawyer_reviews_view, name='lawyer_reviews'),
]
