# Generated by Django 5.2.7 on 2025-11-12 22:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('position', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='documents.documentcomment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
