# Generated by Django 5.2.7 on 2025-11-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentComment',
        ),
    ]
