"use client"

import { ShieldAlert } from "lucide-react"
import { Link } from "react-router-dom"
import React from "react"

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <section className="py-16 md:py-20">
        <div className="w-full px-4 sm:px-6 lg:px-8 max-w-3xl mx-auto text-center">
          <div className="inline-flex items-center px-3 py-1 border border-border rounded-full text-xs font-medium text-muted-foreground mb-6">
            Legal
          </div>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold leading-tight tracking-tight text-foreground font-serif mb-6">
            Disclaimer
          </h1>
          <p className="text-sm text-muted-foreground">Last updated: January 2025</p>
        </div>
      </section>

      <section className="py-16 md:py-20 border-t border-border">
        <div className="w-full px-4 sm:px-6 lg:px-8 max-w-3xl mx-auto">
          <div className="bg-muted/50 border border-border rounded-xl p-6 md:p-8 mb-8">
            <div className="flex items-center gap-3 mb-4">
              <ShieldAlert className="w-5 h-5 text-muted-foreground" />
              <h2 className="text-xl font-bold font-serif text-foreground">
                Not Legal Advice
              </h2>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              AdvocAI is an AI-powered drafting and analysis tool. We are not a law firm, and nothing on this platform constitutes legal advice. Our AI can help you generate preliminary drafts of legal documents, explain legal terminology in plain language, and flag clauses that may warrant attention — but it cannot interpret your specific situation, predict legal outcomes, or replace the judgment of a qualified legal professional.
            </p>
          </div>

          <div className="space-y-8">
            <div>
              <h2 className="text-xl font-bold font-serif text-foreground mb-3">AI-Generated Content</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Documents and analyses generated by AdvocAI are produced by artificial intelligence and should be treated as starting points, not finished legal instruments. AI-generated content may contain errors, may not account for your specific jurisdiction or circumstances, and may not reflect recent changes in law.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold font-serif text-foreground mb-3">No Attorney-Client Relationship</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Use of AdvocAI does not create an attorney-client relationship between you and AdvocAI or any of its affiliates. Our platform is a tool, not a legal service provider.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold font-serif text-foreground mb-3">Consult a Professional</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                For any real legal matter — whether reviewing a contract before signing, navigating a dispute, or ensuring compliance with local regulations — you should consult a qualified, licensed lawyer. Our{" "}
                <Link to="/lawyer-connect" className="text-foreground font-medium underline underline-offset-2 hover:text-primary transition-colors">
                  Lawyer Connect
                </Link>{" "}
                feature exists specifically to help you find the right legal professional when you need one.
              </p>
            </div>

            <div>
              <h2 className="text-xl font-bold font-serif text-foreground mb-3">Third-Party Links</h2>
              <p className="text-sm text-muted-foreground leading-relaxed">
                AdvocAI may contain links to third-party websites or services. We are not responsible for the content, privacy practices, or accuracy of information on any third-party site.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
